---
title: "Practica.TecnicasdeCampo.MasterBiologiaIntegrada.UniversidadSevilla"
author: "Marcial"
date: "05/21/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---
1. Install and load packages

```{r}
#install.packages("picante")
#This will install also package dependences
library(picante)
#This will also load package dependences
#library(ape)
#library(vegan)
#library(permute)
#library(lattice)
#library(nlme)


#devtools::install_github("jinyizju/V.PhyloMaker")
library(V.PhyloMaker)

```


3. Frequency matrix.

```{r}
mydata <- read.csv("Transectos.csv", sep = ",")

mydata

```



3. Create your tree and plot

```{r}

names(mydata)
genera<-sapply(strsplit(as.character(mydata[,1]),"_"),function(x) x[1])
epithet<-sapply(strsplit(as.character(mydata[,1]),"_"),function(x) x[2])
infrasp <-sapply(strsplit(as.character(mydata[,1]),"_"),function(x) x[3])

infrasp

library(Taxonstand)
correctednames <- TPL(genus = genera, species = epithet, infrasp = infrasp, infra = F, corr = TRUE, diffchar = 2, max.distance = 1,version = "1.1", encoding = "UTF-8", author = TRUE,drop.lower.level = FALSE, file = "", silent = TRUE, repeats = 6)
write.csv(correctednames,"correctednames.csv", row.names = FALSE)


species <- paste(genera,epithet, sep = "_")
species
duplicated(species)

#mydata[,5] <- as.character(mydata[,5])
#mydata[,5][duplicated(species)]
#species[duplicated(species)]
#species[duplicated(species)] <- mydata[,5][duplicated(species)]

#duplicated(species)

#mydata[,5][duplicated(species, fromLast = TRUE)]
#species[duplicated(species, fromLast = TRUE)]
#species[duplicated(species, fromLast = TRUE)] <- mydata[,5][duplicated(species, fromLast = TRUE)]

#duplicated(species)

mydata[,2] <- as.character(mydata[,2])
mydata[,2][mydata[,2]=="Leguminosae"] <-"Fabaceae" 
mydata[,2][mydata[,2]=="Compositae"] <-"Asteraceae"
mydata[,2][mydata[,2]=="Palmae"] <-"Arecaceae"
mydata[,2][mydata[,2]=="Droseraceae"] <-"Drosophyllaceae"
mydata[,2][mydata[,2]=="Liliaceae"] <-"Asparagaceae"
mydata[,2][mydata[,2]=="Adoxaceae"] <-"Caprifoliaceae"
mydata[,2][mydata[,2]=="Adoxaceae"] <-"Caprifoliaceae"
mydata[,2][mydata[,2]=="Labiatae"] <-"Lamiaceae"

#Rhamnus is from Rhamnaceae, no EUPHORBIACEAE
       


data <- data.frame(species = species, genus = genera, family = mydata[,2])
my.phylo.maker <- phylo.maker(data, tree = GBOTB.extended, nodes = nodes.info.1, output.sp.list = TRUE, output.tree = FALSE, scenarios = c("S1","S2","S3"), r = 1)


speciesnamesversions <- cbind(as.character(mydata[,1]), paste(correctednames$New.Genus,correctednames$New.Species, sep = "_"), species )

my.phylo.maker$scenario.3$tip.label <- speciesnamesversions[,1][match(my.phylo.maker$scenario.3$tip.label,speciesnamesversions[,3])]
pdffn = paste0("myphylo", ".scenario3.pdf")
pdf(file=pdffn, width=6, height=18)
plot(my.phylo.maker$scenario.3, cex = 0.5)
dev.off()
write.tree(my.phylo.maker$scenario.3, file = "mytree3.tree")

my.phylo.maker$scenario.2$run.1$tip.label <- speciesnamesversions[,1][match(my.phylo.maker$scenario.2$run.1$tip.label,speciesnamesversions[,3])]
pdffn = paste0("myphylo", ".scenario2.pdf")
pdf(file=pdffn, width=6, height=18)
plot(my.phylo.maker$scenario.2$run.1, cex = 0.5)
dev.off()
write.tree(my.phylo.maker$scenario.2$run.1, file = "mytree2.tree")

my.phylo.maker$scenario.1$tip.label <- speciesnamesversions[,1][match(my.phylo.maker$scenario.1$tip.label,speciesnamesversions[,3])]
pdffn = paste0("myphylo", ".scenario1.pdf")
pdf(file=pdffn, width=6, height=18)
plot(my.phylo.maker$scenario.1, cex = 0.5)
dev.off()
write.tree(my.phylo.maker$scenario.1, file = "mytree1.tree")


#speciesnamesversions2 <- cbind(as.character(mydata[,1]), paste(correctednames$New.Genus,correctednames$New.Species, correctednames$New.Infraspecific, sep = "_"), species )
#speciesnamesversions2[,2] <- sub("_$", "", speciesnamesversions2[,2])
#speciesnamesversions2

```


4. Calculate phylogenetic diversity statistics.

```{r}

#color.plot.phylo(my.phylo.maker$scenario.2$run.1, mydata, names(mydata)[34], "Species", leg.cex = 0.6, main = paste0(names(mydata)[34]))
#color.plot.phylo(my.phylo.maker$scenario.2$run.1, mydata, names(mydata)[12], "Species", leg.cex = 0.6, main = paste0(names(mydata)[12]))
#color.plot.phylo(my.phylo.maker$scenario.2$run.1, mydata, names(mydata)[9], "Species", leg.cex = 0.6, main = paste0(names(mydata)[9]))
#color.plot.phylo(my.phylo.maker$scenario.2$run.1, mydata, names(mydata)[10], "Species", leg.cex = 0.6, main = paste0(names(mydata)[10]))
#color.plot.phylo(my.phylo.maker$scenario.2$run.1, mydata, names(mydata)[20], "Species", leg.cex = 0.6, main = paste0(names(mydata)[20]))

#ETC. ETC. ETC.

mytree <- my.phylo.maker$scenario.2$run.1
?pd
#Explore the function and run the examples
dim(mydata)
mydata <- mydata[1:118,5:49]
rownames(mydata) = mydata[,1]
dim(mydata)
mydata <- mydata[,-2]
mydata <- mydata[,-2]

mypd <- pd(t(mydata[,-c(1)]), mytree, include.root=TRUE)
mypd

?mpd
#Explore the function and run the examples

mympd <- mpd(t(mydata[,-c(1)]), cophenetic(mytree), abundance.weighted=T)
mympd
myresults1 <- cbind(mypd, mympd)

?mntd
#Explore the function and run the examples

mymntd <- mntd(t(mydata[,-c(1)]), cophenetic(mytree), abundance.weighted=T)
mymntd
myresults2 <- cbind(myresults1, mymntd)
colnames(myresults2) <- c("PD", "SR", "MPD", "MNTD")
myresults2
write.table(myresults2, file = "diversity_index_results.txt")

mycomdist <- comdist(t(mydata[,-c(1)]), cophenetic(mytree), abundance.weighted=T)
library(cluster)
mycomdist.clusters <- hclust(mycomdist)
pdffn = paste0("mpd", ".phylogeneticbetadiversity.pdf")
pdf(file=pdffn, width=6, height=6)
plot(mycomdist.clusters, main = "Dendrogram based on beta MPD")
dev.off()


mycomdistnt1 <- comdistnt(t(mydata[,-c(1)]), cophenetic(mytree), abundance.weighted=F, exclude.conspecifics = T)
mycomdistnt1.clusters <- hclust(mycomdistnt1)
pdffn = paste0("mntd_excluding", ".phylogeneticbetadiversity.pdf")
pdf(file=pdffn, width=6, height=6)
plot(mycomdistnt1.clusters, main = "Dendrogram based on beta MNTD excluding conspecifics")
dev.off()

mycomdistnt2 <- comdistnt(t(mydata[,-c(1)]), cophenetic(mytree), abundance.weighted=F, exclude.conspecifics = F)
mycomdistnt2.clusters <- hclust(mycomdistnt2)
pdffn = paste0("mntd_including", ".phylogeneticbetadiversity.pdf")
pdf(file=pdffn, width=6, height=6)
plot(mycomdistnt2.clusters, main = "Dendrogram based on beta MNTD including conspecifics")
dev.off()

```


5. We are going to check for phylogenetic clustering and overdispersion
```{r}
my.ses.pd <- ses.pd(t(mydata[,-c(1)]), mytree, null.model = "taxa.labels",
runs = 999)
my.ses.pd
write.table(my.ses.pd, file="ses.pd.result.txt")

my.ses.mpd <- ses.mpd(t(mydata[,-c(1)]), cophenetic(mytree), null.model = "taxa.labels",
abundance.weighted = T, runs = 999)
my.ses.mpd
write.table(my.ses.mpd, file="ses.mpd.result.txt")


my.ses.mntd <- ses.mntd(t(mydata[,-c(1)]), cophenetic(mytree), null.model = "taxa.labels",
abundance.weighted = T, runs = 999)
my.ses.mntd
write.table(my.ses.mntd, file="ses.mntd.result.txt")



?comm.phylo.cor

comm.phylo.cor.r <- comm.phylo.cor(t(mydata[,-c(1)]), mytree, metric="cij",null.model="sample.taxa.labels")
comm.phylo.cor.r
par(mai=c(1.02,0.82,0.82,0.42))
pdffn = paste0("comm.phylo.cor", ".phylogeneticbetadiversity.pdf")
pdf(file=pdffn, width=6, height=6)
hist(comm.phylo.cor.r$random.corrs)
abline(v=comm.phylo.cor.r$obs.corr)
dev.off()

```

6. We are going to make some calculations of phylogenetic distinctivenes

```{r}

?evol.distinct

my.evol.distinct <- evol.distinct(mytree, type = "fair.proportion", scale = FALSE, use.branch.lengths = TRUE)

my.evol.distinct
mean(my.evol.distinct[,2])

mydata$Especie_PL[mydata$Arenas_1 != 0]
speciestoprune <- setdiff(mytree$tip.label,mydata$Especie_PL[mydata$Arenas_1 != 0])
speciestoprune
mytree.Arenas1 <- drop.tip(mytree, speciestoprune)
Arenas1.evol.distinct <- evol.distinct(mytree.Arenas1, type = "fair.proportion", scale = FALSE, use.branch.lengths = TRUE)
mean(Arenas1.evol.distinct[,2])


my.evol.distinct.Arenas_1 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_1 != 0],]
mean(my.evol.distinct.Arenas_1[,2])
my.evol.distinct.Arenas_2 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_2 != 0],]
mean(my.evol.distinct.Arenas_2[,2])
my.evol.distinct.Arenas_3 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_3 != 0],]
mean(my.evol.distinct.Arenas_3[,2])
my.evol.distinct.Arenas_4 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_4 != 0],]
mean(my.evol.distinct.Arenas_4[,2])
my.evol.distinct.Arenas_5 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_5 != 0],]
mean(my.evol.distinct.Arenas_5[,2])
my.evol.distinct.Arenas_6 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_6 != 0],]
mean(my.evol.distinct.Arenas_6[,2])
my.evol.distinct.Arenas_7 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_7 != 0],]
mean(my.evol.distinct.Arenas_7[,2])
my.evol.distinct.Arenas_8 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_8 != 0],]
mean(my.evol.distinct.Arenas_8[,2])
my.evol.distinct.Arenas_9 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_9 != 0],]
mean(my.evol.distinct.Arenas_9[,2])
my.evol.distinct.Arenas_10 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_10 != 0],]
mean(my.evol.distinct.Arenas_10[,2])
my.evol.distinct.Arenas_11 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Arenas_11 != 0],]
mean(my.evol.distinct.Arenas_11[,2])

my.evol.distinct.Alcornocal_1 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Alcornocal_1 != 0],]
mean(my.evol.distinct.Alcornocal_1[,2])
my.evol.distinct.Alcornocal_2 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Alcornocal_2 != 0],]
mean(my.evol.distinct.Alcornocal_2[,2])
my.evol.distinct.Alcornocal_3 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Alcornocal_3 != 0],]
mean(my.evol.distinct.Alcornocal_3[,2])
my.evol.distinct.Alcornocal_4 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Alcornocal_4 != 0],]
mean(my.evol.distinct.Alcornocal_4[,2])
my.evol.distinct.Alcornocal_5 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Alcornocal_5 != 0],]
mean(my.evol.distinct.Alcornocal_5[,2])
my.evol.distinct.Alcornocal_6 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Alcornocal_6 != 0],]
mean(my.evol.distinct.Alcornocal_6[,2])

my.evol.distinct.Brezal_1 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Brezal_1 != 0],]
mean(my.evol.distinct.Brezal_1[,2])
my.evol.distinct.Brezal_2 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Brezal_2 != 0],]
mean(my.evol.distinct.Brezal_2[,2])
my.evol.distinct.Brezal_3 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Brezal_3 != 0],]
mean(my.evol.distinct.Brezal_3[,2])
my.evol.distinct.Brezal_4 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Brezal_4 != 0],]
mean(my.evol.distinct.Brezal_4[,2])
my.evol.distinct.Brezal_5 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Brezal_5 != 0],]
mean(my.evol.distinct.Brezal_5[,2])
my.evol.distinct.Brezal_6 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Brezal_6 != 0],]
mean(my.evol.distinct.Brezal_6[,2])

my.evol.distinct.Caliza_1 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Caliza_1 != 0],]
mean(my.evol.distinct.Caliza_1[,2])
my.evol.distinct.Caliza_2 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Caliza_2 != 0],]
mean(my.evol.distinct.Caliza_2[,2])
my.evol.distinct.Caliza_3 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Caliza_3 != 0],]
mean(my.evol.distinct.Caliza_3[,2])
my.evol.distinct.Caliza_4 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Caliza_4 != 0],]
mean(my.evol.distinct.Caliza_4[,2])
my.evol.distinct.Caliza_5 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Caliza_5 != 0],]
mean(my.evol.distinct.Caliza_5[,2])
my.evol.distinct.Caliza_6 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Caliza_6 != 0],]
mean(my.evol.distinct.Caliza_6[,2])
my.evol.distinct.Caliza_7 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Caliza_7 != 0],]
mean(my.evol.distinct.Caliza_7[,2])
my.evol.distinct.Caliza_8 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Caliza_8 != 0],]
mean(my.evol.distinct.Caliza_8[,2])

my.evol.distinct.Dolomia_1 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Dolomia_1 != 0],]
mean(my.evol.distinct.Dolomia_1[,2])
my.evol.distinct.Dolomia_2 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Dolomia_2 != 0],]
mean(my.evol.distinct.Dolomia_2[,2])
my.evol.distinct.Dolomia_3 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Dolomia_3 != 0],]
mean(my.evol.distinct.Dolomia_3[,2])
my.evol.distinct.Dolomia_4 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Dolomia_4 != 0],]
mean(my.evol.distinct.Dolomia_4[,2])

my.evol.distinct.Quejigal_1 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Quejigal_1 != 0],]
mean(my.evol.distinct.Quejigal_1[,2])
my.evol.distinct.Quejigal_2 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Quejigal_2 != 0],]
mean(my.evol.distinct.Quejigal_2[,2])
my.evol.distinct.Quejigal_3 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Quejigal_3 != 0],]
mean(my.evol.distinct.Quejigal_3[,2])
my.evol.distinct.Quejigal_4 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Quejigal_4 != 0],]
mean(my.evol.distinct.Quejigal_4[,2])

my.evol.distinct.Serpentina_1 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Serpentina_1 != 0],]
mean(my.evol.distinct.Serpentina_1[,2])
my.evol.distinct.Serpentina_2 <- my.evol.distinct[my.evol.distinct[,1] %in% mydata$Especie_PL[mydata$Serpentina_2 != 0],]
mean(my.evol.distinct.Serpentina_2[,2])


```

